// VERSION 260703
// W tym miejscu definiowane są ustawienia domyślne.
// Nie edytuj tego pliku bezpośrednio. Użyj pliku "yt-dlp.ini", aby dostosować ustawienia.

[SWITCH]

stop=0
	// Wyłącza parsowanie strumienia przez to rozszerzenie.
	// 0: Off (domyślnie)  /  1: On
	// Jeżeli wartość ta zmieni się na "-1" z powodu błędu krytycznego, zresetuj ją do 0 
	// i ponownie załaduj skrypt po potwierdzeniu, że nie występują żadne problemy.

[COOKIE]

cookie_file=
//cookie_file=%APPDATA%\PotPlayerMini64\Extension\Media\PlayParse\cookies01.txt
	// Ścieżka do zapisanego pliku cookie.
	// Konieczne jest zalogowanie się na konto w serwisie internetowym.
	// Zbierz pliki cookie z zalogowanych sesji, aby utworzyć ten plik.
	// Zobacz: https://github.com/hgcat-360/PotPlayer-Extension_yt-dlp/wiki/Get-Cookies-and-Login#prepare-a-cookie-file-manually
	// Zobacz także: https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp

cookie_browser=
//cookie_browser=firefox
	// Nazwa przeglądarki, z której mają być automatycznie pobierane pliki cookie.
	// Ignorowane, jeśli ustawiono 'cookie_file'.
	// Uwaga: W systemie Windows dobrze działa tylko "firefox".
	// Aby użyć profilu przeglądarki, dodaj na końcu ":PROFILE".
	// Aby użyć kontenera Firefox, dodaj na końcu "::CONTAINER".
	// Zobacz: https://github.com/hgcat-360/PotPlayer-Extension_yt-dlp/wiki/Get-Cookies-and-Login#automatically-extract-cookies

mark_watched=1
	// Dodaje obejrzane filmy do "Historii oglądania" na Twoim koncie po zalogowaniu.
	// 0: Off  /  1: On (ustawienie domyślne)

[YOUTUBE]

enable_youtube=2
	// Kontroluje sposób obsługi adresów URL w serwisie YouTube.
	// Jeśli wbudowane rozszerzenie YouTube znajduje się powyżej rozszerzenia yt-dlp,
	// to wbudowane rozszerzenie będzie obsługiwać adresy URL serwisu YouTube.
	// Jeśli jedno rozszerzenie pominie zadanie, kolejne rozszerzenie spróbuje je wykonać.
	// 0: Przekaż wszystkie adresy URL YouTube do następnego rozszerzenia
	// 1: Obsługuj filmy, przekazuj listy odtwarzania
	// 2: Obsługuj zarówno filmy, jak i listy odtwarzania (ustawienie domyślne)
	// 3: Obsługuj tylko listy odtwarzania, przekazuj filmy
	// W przypadku ustawienia 2 lub 3 zobacz 'website_playlist_xxx' w sekcji [TARGET].
	// Niektóre listy odtwarzania mogą być traktowane inaczej niż wbudowane zachowanie.

youtube_live=1
	// Obsługuje transmisje na żywo z serwisu YouTube za pomocą yt-dlp.exe.
	// Działa tylko wtedy, gdy 'enable_youtube' jest ustawione na 1 lub 2.
	// W przypadku czatu na żywo zobacz ustawienie 'live_chat' w sekcji [TARGET].
	// Ustaw na 0, aby skorzystać z wbudowanej funkcji PotPlayer, która może umożliwić 
	// przewinięcie strumienia do momentu przed rozpoczęciem oglądania.
	// 0: Off  /  1: On (ustawienie domyślne)

base_lang=
	// Język bazowy dla etykiet menu.
	// Użyj kodu ISO 639 lub aliasu (np. "en", "pl", "pt", "fil", "iw", ...).
	// Niektóre języki wymagają podtagu regionu lub skryptu,
	// np. "zh-CN", "zh-TW", "es-419", "pt-PT", "fr-CA", "sr-Latn".
	// Nie wszystkie języki są obsługiwane w przypadku etykiet menu.
	// Leave blank for auto-detection (ustawienie domyślne).

auto_sub_lang=
//auto_sub_lang=pl, hi, en, ta, te
	// Języki automatycznie generowanych napisów w serwisie YouTube.
	// Jeśli dla tych języków istnieją automatycznie generowane napisy,
	// są one dodawane jako opcje do menu napisów w programie PotPlayer.
	// Używaj kodów ISO 639 lub aliasów. Wiele kodów należy oddzielić przecinkami.
	// Jeśli kod języka ma wiele form, dopasowywane są wszystkie
	// (np. "zh" pasuje do obu "zh-Hans" i "zh-Hant").
	// Pozostaw puste pole, aby wykrycie nastąpiło automatycznie (ustawienie domyślne).
	// Uwaga: YouTube może ograniczyć dostęp do automatycznych napisów po wielokrotnym użyciu.

dubbed_filter=1
	// Filtruje automatycznie dubbingowane ścieżki, jeśli takie istnieją.
	// Pomaga odchudzić menu i szybciej otwierać strumienie w PotPlayer.
	// YouTube oferuje dwa rodzaje automatycznie dubbingowanych utworów: 
	// ścieżki zawierające wyłącznie dźwięk oraz ścieżki wideo z dubbingiem.
	// 0: Nie filtruj ścieżek z dubbingiem
	// 1: Filtruj wszystkie ścieżki z dubbingiem według 'auto_sub_lang' (ustawienie domyślne)
	// 2: Filtruj ścieżki wideo z dubbingiem według języka domyślnego, zachowaj ścieżki wyłącznie audio

keep_tab_playlist=1
	// Pozostawia listy odtwarzania nierozwinięte podczas importowania kart kanału YouTube.
	// Dotyczy zakładek Polecane (Strona główna), Listy odtwarzania, Wydawnictwa i Podcasty.
	// Możesz rozwinąć listę odtwarzania później, klikając ją dwukrotnie w krótkich odstępach czasu.
	// Ustaw wartość 0, aby od razu rozwinąć wszystkie listy odtwarzania.
	// Działa tylko wtedy, gdy 'enable_youtube' jest ustawione na 2 lub 3,
	// a to rozszerzenie znajduje się powyżej wbudowanego rozszerzenia YouTube.
	// 0: Off  /  1: On (ustawienie domyślne)

sponsor_block=
//sponsor_block=sponsor, interaction, selfpromo, music_offtopic
//sponsor_block=all, -poi_highlight
	// Dodaje rozdziały SponsorBlock do filmów na YouTube.
	// Zobacz: https://github.com/hgcat-360/PotPlayer-Extension_yt-dlp/wiki/SponsorBlock-on-YouTube
	// Zobacz rónież: https://wiki.sponsor.ajay.app/w/Guidelines
	// Wpisz wybrane kategorie. Dostępne kategorie:
	// poi_highlight, sponsor, interaction, selfpromo, filler, hook, preview, 
	// intro, outro, music_offtopic, all. (Od wysokiego do niskiego priorytetu)
	// Oddzielaj wiele kategorii przecinkami. Przedrostek "-" oznacza wykluczenie danego elementu.

player_client=default
	// Klienci, z których należy pobrać dane wideo.
	// Wpisz wiele klientów, oddzielając je przecinkami.
	// Zobacz: https://github.com/yt-dlp/yt-dlp/blob/master/README.md#extractor-arguments

#po_token=
//po_token=web.gvs+XXX,web_safari.gvs+YYY
	// Token PO, używany z plikami cookie ('cookie_file' lub 'cookie_browser').
	// Format: "CLIENT.CONTEXT+PO_TOKEN" (Przyjęty kontekst: GVS)
	// Jeśli potrzebujesz więcej niż jednego tokenu, rozdziel je przecinkami.
	// Zobacz: https://github.com/yt-dlp/yt-dlp/blob/master/README.md#extractor-arguments
	// Zobacz także: https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide
	// Pozostaw puste, jeśli używasz dostawcy POT.

#potoken_bgutil_http=
//potoken_bgutil_http="base_url=http://127.0.0.1:8080"
	// Dla dostawcy POT BgUtils (Brainicism).
	// Zobacz: https://github.com/Brainicism/bgutil-ytdlp-pot-provider
	// Format: --extractor-args "youtubepot-bgutilhttp:XXXXX"
	// Potrzebuje ciasteczek ('cookie_file' lub 'cookie_browser').

#potoken_bgutil_script=
//potoken_bgutil_script="server_home=/path/to/bgutil-ytdlp-pot-provider/server"
	// Dla dostawcy POT BgUtils (Brainicism).
	// Zobacz: https://github.com/Brainicism/bgutil-ytdlp-pot-provider
	// Format: --extractor-args "youtubepot-bgutilscript:YYYYY"
	// Potrzebuje ciasteczek ('cookie_file' or 'cookie_browser').

[TARGET]

website_playlist_standard=1
	// Określa sposób obsługi list odtwarzania na stronie internetowej, o ile jest to obsługiwane.
	// Zazwyczaj listy odtwarzania rozwijają się po dodaniu do albumu w programie PotPlayer.
	// W przypadku list odtwarzania YouTube działa tylko wtedy, gdy 'enable_youtube' jest ustawione na 2 lub 3.
	// Niektóre listy odtwarzania mogą wymagać dużo czasu na zebranie metadanych elementów, 
	// więc dostosuj 'playlist_metadata_timeout' zgodnie z potrzebami.
	// 0: Nie rozwijaj na początku
	// 1: Rozwiń, jeśli adres URL jest czystą listą odtwarzania bez wideo ID (ustawienie domyślne)
	// 2: Rozwiń, jeśli adres URL zawiera listę odtwarzania
	// W przypadku ustawienia 0 kliknij dwukrotnie listę odtwarzania, aby ją rozwinąć.
	// W przypadku ustawienia 2 strona może nie wyglądać jak lista odtwarzania.

website_playlist_each=youtube: 1, youtu.be: 1, bilibili.com: 2
	// Określa sposób obsługi list odtwarzania dla poszczególnych stron internetowych.
	// Ma pierwszeństwo przed 'website_playlist_standard'.
	// Format: "key: value," gdzie klucz jest ciągiem znaków w domenie adresu URL, 
	// a wartość (0, 1, 2) ma takie samo znaczenie jak w 'website_playlist_standard'.

playlist_items_timeout=0
	// Czas referencyjny w sekundach potrzebny na zebranie adresów URL elementów na liście odtwarzania.
	// Po tym czasie proces się zatrzymuje i na liście jest mniej pozycji.
	// W przypadku dużych list odtwarzania prędkość przetwarzania jest znacznie wolniejsza, jeśli ustawiono limit czasu.
	// Ustaw na 0, aby nie stosować ograniczeń (ustawienie domyślne).

playlist_metadata_timeout=30
	// Czas odniesienia w sekundach dla gromadzenia metadanych elementów listy odtwarzania.
	// Po upływie tego czasu gromadzenie metadanych zostaje wstrzymane, a elementy są natychmiast wyświetlane na liście.
	// Ten limit czasu nie jest stosowany, gdy elementy wczytują się szybko w niektórych witrynach internetowych.
	// Domyślna wartość to 30. Ustaw wartość 0, aby usunąć ograniczenie. 

playlist_show_timeout=1
	// Wyświetla elementy z list odtwarzania witryny, nawet jeśli ich metadane nie zostały jeszcze zebrane  
	// z powodu przekroczenia limitu czasu. Wyjątkiem są niektóre typy list odtwarzania.
	// Jeśli 'playlist_metadata_timeout' jest zbyt krótki, 
	// w widoku albumu może pojawić się wiele elementów bez tytułu.
	// 0: Off  /  1: On (ustawienie domyślne)
	
playlist_expand_mode=1
	// Kontroluje, gdzie po dwukrotnym kliknięciu rozwija się lista odtwarzania witryny.
	// Dotyczy list odtwarzania dodanych do albumów bez ich rozwijania.
	// 0: Dół domyślnego albumu
	// 1: Dół bieżącego albumu (domyślnie)
	// 2: Obok bieżącego elementu
	// 10: Odtwórz kolejkę w nowym oknie
	// W przypadku albumu z zewnętrzną listą odtwarzania opcja 2 działa tak samo jak opcja 1.

direct_file_info=1
	// Ustawia metadane dla bezpośrednich linków do plików wideo, audio lub obrazów w sieci.
	// (data i domena serwera, wraz z miniaturą z samego pliku)
	// yt-dlp.exe nie jest używany w tym zadaniu.
	// Uwaga: Wykrywanie rzeczywistego pliku nie zawsze jest dokładne.
	// 0: Off  /  1: On (ustawienie domyślne)

m3u8_hls=1
	// Wykorzystuje plik yt-dlp.exe do obsługi adresów URL M3U8 (*.m3u8) w sieci.
	// Jeśli treść zawiera tagi HLS, adres URL jest traktowany jako strumień HLS.
	// Jeśli są dostępne, wyświetlane są dostępne formaty jakości.
	// Jeżeli jest to czysta lista odtwarzania, jest ona rozwijana w widoku albumu.
	// 0: Off  /  1: On (ustawienie domyślnie)

live_chat=1
	// Obsługuje czat na żywo. 
        // Wspiera serwisy YouTube, Twitch, Kick, CHZZK i Rumble.
	// Panel czatu można domyślnie wyświetlić za pomocą klawisza [F9].
	// Do czatu na żywo używana jest wewnętrzna przeglądarka Edge (WebView2) aplikacji PotPlayer.
	// W przypadku serwisu YouTube to ustawienie jest ignorowane, jeśli parametr 'youtube_live' ma wartość 0.
	// Aby dołączyć do czatu na YouTube Live, zaloguj się na swoje konto:
	// [Preferencje] > [Rozszerzenia] > [Konto internetowe]
	// 0: Off  /  1: On (ustawienie domyślne)

rss_playlist=1
	// Używa yt-dlp.exe do obsługi kanałów RSS w sieci, zwykle kończących się na ".xml".
	// Po otwarciu adresu URL kanału RSS wymienione elementy 
	// zostaną wyodrębnione i zaimportowane do albumu.
	// 0: Off  /  1: On (ustawienie domyślne)

radio_info=1
	// Zbiera metadane dotyczące radia internetowego (nazwa stacji, itp.).
	// Obsługiwane są Shoutcast i Icecast.
	// To rozszerzenie obsługuje metadane radiowe bezpośrednio, bez użycia pliku yt-dlp.exe.
	// Uwaga: Dynamiczne tytuły utworów są wyświetlane dzięki wbudowanej funkcji programu PotPlayer.
	// 0: Off  /  1: On (ustawienie domyślne)
	
radio_thumbnail=1
	// Wyświetla w widoku albumu miniatury stacji radiowych online.
	// Pliki graficzne (yt-dlp_radio*.jpg) należy umieścić w folderze skryptów.
	// 0: Off  /  1: On (ustawienie domyślne)

shoutcast_playlist=0
	// Zarządza listami odtwarzania Shoutcast bezpośrednio, bez ich rozwijania.
	// (PLS, M3U, XSPF -- pliki tunein-station z http://yp.shoutcast.com/)
	// Pobiera nazwy stacji i, jeśli są dostępne, opcje serwera, które można wybrać.
	// Program yt-dlp.exe nie działa z listami odtwarzania Shoutcast.
	// Jeżeli ustawione na 0, rozwija adresy URL serwera po dodaniu do albumu.
	// 0: Off (ustawienie domyślne)  /  1: On

[FORMAT]

reduce_formats=0
	// Zmniejsza liczbę formatów, gdy w menu jakości pojawia się ich wiele.
	// Pomaga uprościć menu i przyspieszyć otwieranie strumieni w programie PotPlayer.
	// Ustawienie 1 jest przydatne w przypadku nieograniczonego dostępu szerokopasmowego.
	// 0: Nie zmniejszaj (ustawienie domyślne)
	// 1: Zmniejsz liczbę niskiej jakości
	// 2: Zmniejsz liczbę wysokiej jakości
	// 3: Filtruj według rozdzielczości od SD do FullHD

remove_duplicate_quality=1
	// Ukrywa formaty o zduplikowanej jakości i typie w menu jakości.
	// 0: Off  /  1: On (ustawienie domyślne)

twitch_live_vod=0
	// Próbuje odtwarzać transmisje na żywo jako treści VOD (wideo na żądanie) na platformie Twitch.
	// Wyświetlane są poprzednie rozdziały, a reklamy mogą zostać usunięte.
	// Dzięki filtrowi "Wbudowane źródło HLS" aplikacji PotPlayer 
	// możliwe jest przewinięcie transmisji na żywo do początku.
	// Zobacz: https://github.com/hgcat-360/PotPlayer-Extension_yt-dlp/wiki/Streaming-Source-Filter
	// Jeśli to się nie powiedzie, program yt-dlp.exe uruchomi się ponownie, działając w trybie standardowym.
	// 0: Off (ustawienie domyślne)  /  1: On

title_live_prefix="{LIVE} "
//title_live_prefix="[ON AIR] "
	// Tekst umieszczony na początku tytułów transmisji na żywo.
	// Służy do transmisji na żywo prowadzonych przez konkretny kanał lub osobę publikującą treści.
	// Użyj cudzysłowów, aby zachować spację na końcu.

title_channel_standard=1
	// W razie potrzeby dodaje nazwę kanału lub autora na początku tytułu.
	// 0: Nie dodawaj
	// 1: Dodaj tylko do transmisji na żywo (ustawienie domyślne)
	// 2: Dodaj do wszystkich treści, jeśli są dostępne

title_channel_each=youtube: 0, youtu.be: 0, twitch: 2, kick: 2, facebook: 2, chzzk: 2
	// Dodaje nazwę kanału lub autora do tytułu każdej strony internetowej.
	// Ma pierwszeństwo przed parametrem 'title_channel_standard'.
	// Format: "key: value," gdzie key to ciąg znaków określający domenę w adresie URL,  
	// a wartość (0, 1, 2) ma takie samo znaczenie jak w polu 'title_channel_standard'.

title_channel_separator=" - "
	// Tekst umieszczany między nazwiskiem autora a tytułem w przypadku użycia „title_channel_xxx”.
	// Używaj cudzysłowów, aby zachować spacje po obu stronach.

title_alt_detail=1
	// Używa "alt_title", jeśli jest bardziej szczegółowy niż tytuł domyślny.
	// 0: Off  /  1: On (ustawienie domyślne)

title_multi_lines=0
	// Zachowuje tytuły w wielu wierszach, jeśli zawierają znaki końca wiersza.
	// Tytuły wielowierszowe są łatwiejsze do odczytania w dymku.
	// 0: Off (ustawienie domyślne)  /  1: On

title_max_length=250
	// Maksymalna długość tytułu strumienia.
	// Jeśli tytuł jest dłuższy niż ta wartość, zostanie skrócony.
	// Ustaw na 0, aby nie stosować ograniczeń (Domyślnie: 250, Dopuszczalna minimalna wartość: 30).

[NETWORK]

cache_time_item=120
	// Czas przechowywania w pamięci podręcznej dla każdego strumienia, w minutach.
	// Gdy to rozszerzenie zgromadzi linki URL i metadane, nie będzie ponownie korzystać   
	// z programu yt-dlp.exe w odniesieniu do tego samego strumienia, dopóki nie upłynie ten czas.
	// Wszystkie pamięci podręczne są czyszczone podczas wczytywania ustawień rozszerzeń lub przy zamykaniu programu PotPlayer.
	// Jeśli pojawi się błąd odtwarzania, spróbuj ponownie załadować stronę, pomijając zawartość pamięci podręcznej.
	// Aby ponownie załadować adres URL bez korzystania z pamięci podręcznej, kliknij dwukrotnie na dany element w krótkich odstępach czasu.
	// Uwaga: Nie obejmuje to samych danych wideo ani audio.
	// Default: 120 minut (zalecane).
	// Ustaw wartość 0, aby wyłączyć limit (niezalecane).

cache_time_playlist=24
	// Czas przechowywania w pamięci podręcznej dla każdej listy odtwarzania, w godzinach.
	// Wszystkie pamięci podręczne są czyszczone podczas wczytywania ustawień rozszerzeń lub przy zamykaniu programu PotPlayer.
	// Default: 24 godziny. Ustaw wartość 0, aby usunąć ograniczenie.

proxy=
//proxy=socks5://user:pass@127.0.0.1:1080/
	// Proxy address for HTTP/HTTPS/SOCKS.

#socket_timeout=

#source_address=

#geo_verification_proxy=

#xff=

ip_version=0
	// Wersja IP do wykorzystania we wszystkich połączeniach.
	// 0: Domyślne
	// 4: IPv4
	// 6: IPv6

no_check_certificates=1
	// Wyłącza sprawdzanie certyfikatu HTTPS.
	// Umożliwia dostęp nawet jeśli certyfikat serwera wygasł.
	// 0: Off  /  1: On (ustawienie domyślne)

referer=
	// Adres URL odsyłacza. Używany tylko wtedy, gdy dostęp do yt-dlp jest niedozwolony.
	// W większości przypadków fikcyjny adres URL pełni rolę źródła odsyłającego dla odtwarzania, 
	// dlatego należy go ustawić tylko wtedy, gdy wymagane jest konkretne źródło odsyłające.
	// Po nawiązaniu dostępu PotPlayer zapisuje domenę docelową 
	// i jej adresata jako parę.

[MAINTENANCE]

console_out=0
	// Wyświetla okno konsoli z komunikatami i błędami.
	// Aby zamknąć, ustaw tę opcję na 0 i uruchom ponownie PotPlayer.
	// Ostrzeżenie: Rozszerzenia przestają działać po zaznaczeniu tekstu w konsoli.
	// Zobacz: https://github.com/hgcat-360/PotPlayer-Extension_yt-dlp/wiki/Console-Log-Output-Notes
	// 0: Ukryj (domyślnie)
	// 1: Pokaż główne informacje
	// 2: Pokaż szczegółowe informacje
	// 3: Pokaż wszystkie informacje z danymi JSON yt-dlp i serwera HTTP

ytdlp_location=
	// Ścieżka folderu, w którym należy umieścić plik yt-dlp.exe.
	// Wprowadź pełną ścieżkę do folderu bez zmiennych środowiskowych.
	// Jeśli pole jest puste, używany jest folder "Module" PotPlayer (ustawienie domyślne).

update_ytdlp=0
	// Automatycznie aktualizuje plik yt-dlp.exe, jeśli w sieci zostanie znaleziona nowsza wersja.
	// W przypadku korzystania z kompilacji nocnej pobierana jest najnowsza wersja nocna.
	// Mogą być konieczne uprawnienia administratora, aby PotPlayer mógł zastąpić plik yt-dlp.exe.
	// Możesz zmienić folder 'ytdlp_location', aby uzyskać uprawnienia do zapisu.
	// 0: Nie aktualizuj automatycznie (ustawienie domyślne)
	// 1: Automatyczna aktualizacja, gdy używany jest plik yt-dlp.exe
	// 2: Zaktualizuj raz, a następnym razem otwórz panel informacyjny yt-dlp w ustawieniach

ytdlp_hash=
	// Wartość hash pliku yt-dlp.exe.
	// Nie usuwaj tego.

