[DirectoriesToPreserve]
PreserveDirectory1=App\PotPlayer64\Capture
PreserveDirectory2=App\PotPlayer64\Playlist
PreserveDirectory3=App\PotPlayer64\Module
PreserveDirectory4=App\PotPlayer64\Skins

[FilesToPreserve]
PreserveFile1=App\PotPlayer64\PotLauncher.ini

;[OptionalComponents]
;OptionalComponents=true
;MainSectionTitle=PotPlayer64 Portable [Wymagane]
;MainSectionDescription=Zainstaluj przenośną aplikację
;OptionalSectionTitle=Dodatkowe komponenty
;OptionalSectionDescription=Dodatkowe pliki i rozszerzenia (ExtTorrent, Twich, YouTubeMod, deno, yt-dlp)
;OptionalSectionInstalledWhenSilent=true
;OptionalDirectory1=App\PotPlayer64\Extension\Lib
;OptionalDirectory2=App\PotPlayer64\Extension\Media\SourceReader
;OptionalFile1=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - LibTorrent.as
;OptionalFile2=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - LibTorrent.ico
;OptionalFile3=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - Twitch.as
;OptionalFile4=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - Twitch.ico
;OptionalFile5=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - yt-dlp #1.ico
;OptionalFile6=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - yt-dlp #2.ico
;OptionalFile7=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - yt-dlp.as
;OptionalFile8=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - yt-dlp.ico
;OptionalFile9=App\PotPlayer64\Extension\Media\PlayParse\yt-dlp_default.ini
;OptionalFile10=App\PotPlayer64\Extension\Media\PlayParse\yt-dlp_playlist.jpg
;OptionalFile11=App\PotPlayer64\Extension\Media\PlayParse\yt-dlp_radio1.jpg
;OptionalFile12=App\PotPlayer64\Extension\Media\PlayParse\yt-dlp_radio2.jpg
;OptionalFile13=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - yt-dlp-DV.as
;OptionalFile14=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - yt-dlp-DV.ico
;OptionalFile15=App\PotPlayer64\Extension\Media\PlayParse\config.ini
;OptionalFile16=App\PotPlayer64\Extension\Media\UrlList\MediaUrlList - Twitch.as
;OptionalFile17=App\PotPlayer64\Extension\Media\UrlList\MediaUrlList - Twitch.ico
;OptionalFile18=App\PotPlayer64\Module\deno.exe
;OptionalFile19=App\PotPlayer64\Module\yt-dlp.exe
