[DirectoriesToPreserve]
PreserveDirectory1=App\PotPlayer64\Capture
PreserveDirectory2=App\PotPlayer64\Playlist
PreserveDirectory3=App\PotPlayer64\Module
PreserveDirectory4=App\PotPlayer64\Skins

[FilesToPreserve]
PreserveFile1=App\PotPlayer64\PotLauncher.ini

;[OptionalComponents]
;OptionalComponents=true
;MainSectionTitle=PotPlayer64 Portable [Wymagane]
;MainSectionDescription=Zainstaluj przenośną aplikację
;OptionalSectionTitle=Dodatkowe komponenty
;OptionalSectionDescription=Dodatkowe pliki i rozszerzenia (ExtTorrent, Twich, YouTubeMod, deno, yt-dlp)
;OptionalSectionInstalledWhenSilent=true
;OptionalDirectory1=App\PotPlayer64\Extension\Lib
;OptionalDirectory2=App\PotPlayer64\Extension\Media\SourceReader
;OptionalFile1=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - LibTorrent.as
;OptionalFile2=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - LibTorrent.ico
;OptionalFile3=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - Twitch.as
;OptionalFile4=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - Twitch.ico
;OptionalFile5=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - yt-dlp #1.ico
;OptionalFile6=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - yt-dlp #2.ico
;OptionalFile7=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - yt-dlp.as
;OptionalFile8=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - yt-dlp.ico
;OptionalFile9=App\PotPlayer64\Extension\Media\PlayParse\yt-dlp_default.ini
;OptionalFile10=App\PotPlayer64\Extension\Media\PlayParse\yt-dlp_playlist.jpg
;OptionalFile11=App\PotPlayer64\Extension\Media\PlayParse\yt-dlp_radio1.jpg
;OptionalFile12=App\PotPlayer64\Extension\Media\PlayParse\yt-dlp_radio2.jpg
;OptionalFile13=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - yt-dlp-DV.as
;OptionalFile14=App\PotPlayer64\Extension\Media\PlayParse\MediaPlayParse - yt-dlp-DV.ico
;OptionalFile15=App\PotPlayer64\Extension\Media\PlayParse\config.ini
;OptionalFile16=App\PotPlayer64\Extension\Media\UrlList\MediaUrlList - Twitch.as
;OptionalFile17=App\PotPlayer64\Extension\Media\UrlList\MediaUrlList - Twitch.ico
;OptionalFile18=App\PotPlayer64\Module\deno.exe
;OptionalFile19=App\PotPlayer64\Module\yt-dlp.exe

[DownloadFiles]
AdditionalInstallSize=59536
DownloadURL=https://github.com/denoland/deno/releases/download/v2.9.4/deno-x86_64-pc-windows-msvc.zip
DownloadName=deno-x86_64-pc-windows-msvc
DownloadFilename=deno-x86_64-pc-windows-msvc.zip
DownloadSHA256=68ed08b05c56cf887e9aa509947dc3f468f7e12f47a13e5c1abd51d46d1453ef
AdvancedExtract1To=App\PotPlayer64\Module
AdvancedExtract1Filter=*
Download2URL=https://github.com/yt-dlp/yt-dlp/releases/download/2026.07.04/yt-dlp.exe
Download2Name=yt-dlp
Download2Filename=yt-dlp.exe
Download2SHA256=52fe3c26dcf71fbdc85b528589020bb0b8e383155cfa81b64dd447bbe35e24b8
Download2To=App\PotPlayer64\Module
